services:
  nginx:
    image: nginx:alpine
    container_name: insurance_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - insurance-network
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: insurance_php
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - insurance-network
    restart: unless-stopped

networks:
  insurance-network:
    driver: bridge